name: Helm Lint

on:
  pull_request:
    branches: [main]

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      #Lint
      - name: Run Shell
        run: |
          # curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          # sudo apt-get install apt-transport-https --yes
          # echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          # sudo apt-get install helm
          sudo apt-get update
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          pwd
          cd appdeployment
          helm lint .
          helm template .
